print("==========================")
print("   FORM PENDAFTARAN BIODATA SISWA   ")
print("==========================")

nama = input("Nama Lengkap: ")
jurusan = input("Jurusan: ")
kelas = input("Kelas (X/XI/XII): ")
hobi = input("Hobi Utama: ")
cita = input("Cita-cita: ")
tahun_lahir = input("Tahun Lahir: ")
umur = 2026 - int(tahun_lahir)

print("==========================")
print("   KARTU PROFIL DIGITAL SISWA   ")
print("==========================")

print(f"Nama : {nama} ")
print(f"Kelas : {kelas} - {jurusan}")
print(f"Umur : {umur}")
print(f"Hobi : {hobi}")
print(f"Cita-Cita : {cita}")
print(f"Pesan Motivasi : semangat ya {nama}, pasti kamu bisa")