print("=" * 40)
print("FORM PENDAFTARAN BIODATA SISWA")
print("=" * 40)

nama = input("Nama Lengkap: ")
jurusan = input("Jurusan: ")
kelas = input("Kelas (X/XI/XII): ")
hobi = input("Hobi Utama: ")
cita = input("Cita Cita: ")
tahun = input("Tahun Lahir: ")
umur = 2026 - int(tahun)
print("=" * 40)
print("KARTU PROFIL DIGITAL SISWA")
print("=" * 40)
print("Nama     : " + nama)
print("Jurusan     : " + jurusan)
print("Kelas     : " + kelas)
print("Hobi     : " + hobi)
print("Cita-Cita     : " + cita)
print("Tahun Lahir     : " + tahun)
print("Tahun Lahir : " + str(umur))
