print("=" * 40)
print("     FORM PENDAFTARAN SISWA ")
print("=" * 40)
nama = input("Nama Lengkap = ")
juruan = input("Jurusan = ")
kelas = input("kelas X/XI/XII = ")
hobi = input("hobi = ")
cita = input("cita-cita = ")
lahir = int(input("tahun lahir ="))
tahun = 2026
print("===============================")
print(" KARTU PROFIL DIGITAL SISWA")
print("=============================")
print(f"nama = {nama}")
print(f"jurusan = {juruan}")
print(f"kelas = {kelas}")
print(f"hobi = {hobi}")
print(f"cita-cita {cita}")
print(f"umur = {tahun - lahir} ")
