print("==========================")
print("FORM PENDAFTARAN BIODATA SISWA")
print("==========================")
nama = input("Nama Lengkap : ")
jurusan = input("Jurusan : ")
kelas = input("Kelas (X/XI/XII) : ")
hobi = input("Hobi Utama : ")
cita = input("Cita Cita : ")
lahir = int(input("Tanggal Lahir : "))
usia = 2026
print("==========================")
print("KARTU PROFIL DIGITAL SISWA")
print("==========================")
print(f"Nama : {nama}")
print(f"Jurusan : {jurusan}")
print(f"Kelas : {kelas}")
print(f"Hobi Utama : {hobi}")
print(f"Cita-Cita : {cita}")
print(f"Usia : {usia - lahir} ")